#!/usr/bin/env node
'use strict';

const got = require('got');
const args = process.argv.slice(2);

async function requestClient(url='', c=false) {
  try {
    const response = await got(args[0]);
    console.log('Status: ', response.statusCode);
  } catch (e) {
    console.log(e.response.body);
  }
}

if (args.length === 1) {
  requestClient(args[0]);
} else if (args.length === 2 && (args[1] === '-c' || args[1] === '--continue')) {
  setInterval(() => {
    requestClient(args[0], true);
  }, 1000);
}
